services:
  nodejs:
    build: ./docker/frontend
    container_name: NODEJS
    volumes:
      - ./docker/frontend:/app
    ports:
      - '3000:3000'

  laravel:
    build: ./docker/backend
    container_name: LARAVEL
    volumes:
      - ./docker/backend:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:8.4.7
    container_name: MYSQL
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '3306:3306'
  nginx:
    image: nginx:alpine
    container_name: NGINX
    volumes:
      - ./docker/backend:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8000:8000'
    depends_on:
      - laravel

volumes:
  db_data:
